# Generated by Django 3.1.7 on 2021-04-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userFirstname', models.CharField(max_length=100)),
                ('userLastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100)),
                ('search_date', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Search_history.searchtimemodel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Search_history.alluser')),
            ],
        ),
    ]
