# Generated by Django 3.1.7 on 2021-04-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='search_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Search_history.searchtimemodel'),
        ),
    ]
